import { NextRequest, NextResponse } from "next/server";
import {
  getProject,
  getDonationsByProject,
  getExpensesByProject,
  getInvoicesByProject,
  getProgressByProject,
  getBidDocument,
} from "@/lib/data";

function formatVND(amount: number): string {
  return new Intl.NumberFormat("vi-VN").format(amount) + " VND";
}

function formatDateStr(dateStr: string): string {
  const d = new Date(dateStr);
  return `${String(d.getDate()).padStart(2, "0")}/${String(d.getMonth() + 1).padStart(2, "0")}/${d.getFullYear()}`;
}

export async function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl;
  const projectId = searchParams.get("projectId");
  const format = searchParams.get("format") || "csv";

  if (!projectId) {
    return NextResponse.json({ error: "Missing projectId" }, { status: 400 });
  }

  const project = getProject(projectId);
  if (!project) {
    return NextResponse.json({ error: "Project not found" }, { status: 404 });
  }

  const donations = getDonationsByProject(projectId);
  const expenses = getExpensesByProject(projectId);
  const invoices = getInvoicesByProject(projectId);
  const progress = getProgressByProject(projectId);
  const bid = getBidDocument(projectId);

  if (format === "csv") {
    const lines: string[] = [];
    lines.push("BAO CAO MINH BACH TAI CHINH - " + project.name);
    lines.push("");

    lines.push("TONG QUAN");
    lines.push(`Muc tieu,${formatVND(project.goal)}`);
    lines.push(`Da nhan,${formatVND(project.raised)}`);
    lines.push(`Da chi,${formatVND(project.spent)}`);
    lines.push(`So du,${formatVND(project.raised - project.spent)}`);
    lines.push(`Tien do,${project.completionPercent}%`);
    lines.push("");

    lines.push("NGUON THU");
    lines.push("Ma,Nguoi dong gop,So tien,Ngay,Loi nhan");
    for (const d of donations) {
      const name = d.donor.anonymous ? "An danh" : d.donor.name;
      lines.push(
        `${d.id},${name},${d.amount},${formatDateStr(d.date)},${d.message || ""}`
      );
    }
    lines.push("");

    lines.push("KHOAN CHI");
    lines.push("Ma,Mo ta,Danh muc,So tien,Gia thi truong,Ngay,Duyet boi");
    for (const e of expenses) {
      lines.push(
        `${e.id},"${e.description}",${e.category},${e.amount},${e.marketPrice || "N/A"},${formatDateStr(e.date)},${e.approvedBy}`
      );
    }
    lines.push("");

    lines.push("HOA DON");
    lines.push("Ma,Nha cung cap,So tien,Ngay,Tu dong,Trang thai");
    for (const inv of invoices) {
      lines.push(
        `${inv.id},${inv.vendor},${inv.amount},${formatDateStr(inv.date)},${inv.autoGenerated ? "Co" : "Khong"},${inv.status}`
      );
    }
    lines.push("");

    if (bid) {
      lines.push("DU TOAN HANG MUC");
      lines.push("Ma,Hang muc,Don vi,So luong,Don gia,Thanh tien,Quy cach");
      for (const item of bid.items) {
        lines.push(
          `${item.id},"${item.name}",${item.unit},${item.quantity},${item.unitPrice},${item.totalPrice},"${item.specification}"`
        );
      }
      lines.push("");
      lines.push(`Tong du toan,${formatVND(bid.totalEstimate)}`);
      lines.push("");
    }

    lines.push("TIEN DO");
    lines.push("Ngay,Tieu de,Mo ta,Hoan thanh");
    for (const p of progress) {
      lines.push(
        `${formatDateStr(p.date)},"${p.title}","${p.description}",${p.completionPercent}%`
      );
    }

    const csv = "\uFEFF" + lines.join("\n");
    return new NextResponse(csv, {
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="${project.name.replace(/\s+/g, "_")}.csv"`,
      },
    });
  }

  // PDF format - generate a text-based report
  const lines: string[] = [];
  lines.push("=".repeat(60));
  lines.push("BÁO CÁO MINH BẠCH TÀI CHÍNH");
  lines.push(project.name);
  lines.push("=".repeat(60));
  lines.push("");
  lines.push(`Địa điểm: ${project.location}`);
  lines.push(`Trạng thái: ${project.status}`);
  lines.push(`Thời gian: ${formatDateStr(project.startDate)}${project.endDate ? " - " + formatDateStr(project.endDate) : ""}`);
  lines.push(`Tiến độ: ${project.completionPercent}%`);
  lines.push("");
  lines.push("-".repeat(40));
  lines.push("TỔNG QUAN TÀI CHÍNH");
  lines.push("-".repeat(40));
  lines.push(`Mục tiêu:  ${formatVND(project.goal)}`);
  lines.push(`Đã nhận:   ${formatVND(project.raised)}`);
  lines.push(`Đã chi:    ${formatVND(project.spent)}`);
  lines.push(`Số dư:     ${formatVND(project.raised - project.spent)}`);
  lines.push("");
  lines.push("-".repeat(40));
  lines.push(`NGUỒN THU (${donations.length} khoản)`);
  lines.push("-".repeat(40));
  for (const d of donations) {
    const name = d.donor.anonymous ? "Nhà hảo tâm ẩn danh" : d.donor.name;
    lines.push(`  ${formatDateStr(d.date)} | ${name} | +${formatVND(d.amount)}`);
  }
  lines.push("");
  lines.push("-".repeat(40));
  lines.push(`KHOẢN CHI (${expenses.length} khoản)`);
  lines.push("-".repeat(40));
  for (const e of expenses) {
    lines.push(`  ${formatDateStr(e.date)} | ${e.description} | -${formatVND(e.amount)}`);
    if (e.marketPrice) {
      lines.push(`    Giá thị trường: ${formatVND(e.marketPrice)} | Duyệt bởi: ${e.approvedBy}`);
    }
  }
  lines.push("");
  lines.push("-".repeat(40));
  lines.push(`HÓA ĐƠN (${invoices.length})`);
  lines.push("-".repeat(40));
  for (const inv of invoices) {
    lines.push(`  ${inv.id} | ${inv.vendor} | ${formatVND(inv.amount)} | ${inv.status}`);
  }

  if (bid) {
    lines.push("");
    lines.push("-".repeat(40));
    lines.push("DỰ TOÁN HẠNG MỤC (Bill of Quantities)");
    lines.push("-".repeat(40));
    for (const item of bid.items) {
      lines.push(`  ${item.name}`);
      lines.push(`    ${item.quantity} ${item.unit} x ${formatVND(item.unitPrice)} = ${formatVND(item.totalPrice)}`);
      lines.push(`    Quy cách: ${item.specification}`);
    }
    lines.push(`  TỔNG DỰ TOÁN: ${formatVND(bid.totalEstimate)}`);
  }

  lines.push("");
  lines.push("-".repeat(40));
  lines.push("TIẾN ĐỘ");
  lines.push("-".repeat(40));
  for (const p of progress) {
    lines.push(`  ${formatDateStr(p.date)} [${p.completionPercent}%] ${p.title}`);
    lines.push(`    ${p.description}`);
  }
  lines.push("");
  lines.push("=".repeat(60));
  lines.push("Xuất bởi C-withLove | Nền Tảng Từ Thiện Minh Bạch");
  lines.push(`Ngày xuất: ${formatDateStr(new Date().toISOString())}`);
  lines.push("=".repeat(60));

  const text = lines.join("\n");
  return new NextResponse(text, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition": `attachment; filename="${project.name.replace(/\s+/g, "_")}_BaoCao.txt"`,
    },
  });
}
