export interface Donor {
  id: string;
  name: string;
  anonymous: boolean;
}

export interface Donation {
  id: string;
  projectId: string;
  donor: Donor;
  amount: number;
  currency: string;
  date: string;
  message?: string;
}

export interface Expense {
  id: string;
  projectId: string;
  description: string;
  amount: number;
  currency: string;
  date: string;
  category: string;
  invoiceId?: string;
  approvedBy: string;
}

export interface Invoice {
  id: string;
  projectId: string;
  expenseId: string;
  vendor: string;
  amount: number;
  currency: string;
  date: string;
  autoGenerated: boolean;
  status: "pending" | "verified" | "paid";
  fileUrl?: string;
}

export interface ProgressEntry {
  id: string;
  projectId: string;
  date: string;
  title: string;
  description: string;
  imageUrl?: string;
  completionPercent: number;
}

export type ProjectStatus = "active" | "completed" | "planning";

export interface Project {
  id: string;
  name: string;
  description: string;
  goal: number;
  raised: number;
  spent: number;
  currency: string;
  status: ProjectStatus;
  startDate: string;
  endDate?: string;
  location: string;
  category: string;
  imageUrl: string;
  completionPercent: number;
}

export interface FinancialSummary {
  totalRaised: number;
  totalSpent: number;
  totalProjects: number;
  activeProjects: number;
  currency: string;
}
